### ISSUE TITLE
[Question] Set initial values

### ISSUE THREAD

**Issue by aem** [djodjoni/multiselectspinner#3]
Is there a programmatic way to set the initial values of the spinner or will it show up unpopulated each time?

**Comment by djodjoni** [comment]
you can use `selectItem(0, true/false)` for setting a single item or `setSelectAll(true/false)` for all the items. You can also combine those. I updated the [examples](https://github.com/apptik/multiselectspinner/blob/master/example/src/main/java/io/apptik/widget/multiselectspinner/example/MainActivity.java#L60) so you can check. Let me know if this what you need.

**Comment by aem** [comment]
yep! this is perfect, thanks!!
